jobs:
  include:
    - os: osx
      osx_image: xcode10.1
      language: swift
      xcode_project: TrackedValue.xcodeproj
      xcode_scheme: TrackedValue-Package
      xcode_destination: 'platform=macOS'
      before_install: swift package generate-xcodeproj --enable-code-coverage
      after_success: bash <(curl -s https://codecov.io/bash)

    - os: linux
      language: generic
      env: SWIFT_VERSION=4.2.1
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
