#if !canImport(ObjectiveC)
import XCTest

extension TrackedValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrackedValueTests = [
        ("testEqual", testEqual),
        ("testEqualWhenValueModifiedWithDifferentValue", testEqualWhenValueModifiedWithDifferentValue),
        ("testEqualWhenValueModifiedWithSameValue", testEqualWhenValueModifiedWithSameValue),
        ("testInit", testInit),
        ("testSubscript", testSubscript),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TrackedValueTests.__allTests__TrackedValueTests),
    ]
}
#endif
