name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj --enable-code-coverage

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "TrackedValue.xcodeproj" \
          -scheme "TrackedValue-Package" \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" | xcpretty -c

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - /Applications/Xcode_11.2.app
          - /Applications/Xcode_11.1.app
    steps:
    - uses: actions/checkout@v1

    - name: Test
      run: |
        swift --version
        swift test --parallel
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift_version:
          - "5.1"
    steps:
    - uses: actions/checkout@v1
    
    - name: Test
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        swift --version
        swift test --parallel
      env:
        SWIFT_VERSION: ${{ matrix.swift_version }}
